### ISSUE TITLE
Add Lazy Loading

### ISSUE THREAD

**Issue by royrakesh** [mathisGarberg/angular-folder-structure#1]
Everything is fine just one thing , can you add lazy loading and add some demo modules like about page or contact page , so it will be easy to understand the pattern. 

Thanks.

**Comment by mathisGarberg** [comment]
This will be done ;)

**Comment by mathisGarberg** [comment]
Hi again.

I'v now updated the example to contain lazy loaded modules and some other additional features I've been working with.
