### ISSUE TITLE
The Card layout not updated after card flipped

### ISSUE THREAD

**Issue by clavinovahan** [mathisGarberg/angular-folder-structure#107]
The project downloaded from Github has been compiled and runs fine at local except one thing, 

The Card layout not get updated after card flipped. All the cards just stay at the previous position and not moving vertically to take hold the extra space. However the project in action at 

https://mathisgarberg.github.io/angular-folder-structure/#/auth/login

works fine and the card below the flipped card will move vertically to take space. 

What is the difference between Project code and the code of live demo? There must be some difference.

**Comment by mathisGarberg** [comment]
👍 Since we're using a lib. for the masonry-layout, it's unfortately as easy as you'de expect. I want to move away from the lib. and do everything myself with CSS, so this issue can hopefully be used for that.
