### ISSUE TITLE
Remove @app alias (discussion)

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#13]
A common error developers make is treating themselves like their own vendor.  Such as building an application in the vendors which is dependent on the actual application built at the same time.

In your use of `@app` to alias the `core` module I do not see any benefit.  Including index.ts files to simplify includes inside the application is just more work to maintain.  

I propose we remove the `@app` alias and directly include `core` files using the same relative path.

While I appreciate the artistic quality of using `@app` I do not believe it offers any engineering benefit.  Please comment.

**Comment by mathisGarberg** [comment]
Well. I can see your point, but I'm not certain if this is the correct approach. I can understand the benefit by removing the `index.ts`- and `@app`-alias in favor of using relative paths reduce the maintenance of the codebase, but there are some benefits here as well.

When using relative path to locate files in the `core`-folder, you need to update each path accordingly if you decide to re-locate a folder or file. The main reason I decided to use path-aliases for @app and @env in this application is down to the clean look and feel of the imports. 

The main goal of this repo is however to offer developers a highly scalable and clean codebase, which can easily be applied to personal applications, and reduce tedious maintenance is a big part of that. Creating and updating `index.ts`-files are without a doubt tedious work, but using relative path has some downsides as well.

Will share this question between some devs. to see what they think of it.

Thanks for asking.

**Comment by TomHAnderson** [comment]
One observation: this repo is about directory structure and if the first thing you do is start aliasing the directories and taking them out of the structure; well, that's not what this repo is for.  Certainly aliasing directories has its place and we can address that in the new documentation I've started.

**Comment by dougal83** [comment]
Using alias can also improve clarity. It is down to personal preference but there are some who use it extensively such as in projects like [ngrx](https://github.com/ngrx/platform/tree/master/projects/example-app/src/app).

Personally I like it for readability if nothing else.

**Comment by TomHAnderson** [comment]
Comparing this beginner project to ngrx isn't very fair.  Everyone has to start somewhere and this repository is a good starting point.  I would like this to be an easy starting point for any experienced developer and not require prerequisites like understanding how to structure a directory as an alias.

I'm all for adding links in the documentation for further reading on subjects like aliases and I think the more paths we can create away from this starting point on an app's journey the better.

**Comment by TomHAnderson** [comment]
The approach to aliasing used in core/@app is tedious and must be micro managed.  I found a node module which accomplishes the same thing with just a little configuration.  I've added a link in the documentation:  https://github.com/mathisGarberg/angular-folder-structure/blob/368d55dea38c10f4844a0bf0b965141c97d2f953/.documentation/additional-resources.rst

**Comment by dougal83** [comment]
> Comparing this beginner project to ngrx isn't very fair.

Personally I don't think it is fair to classify a cited example of a feature in use as a comparison to a project in its entirety but that might be just me.

Can I ask if it is wise to suggest introducing unnecessary dependencies to beginners?  You've mentioned a package named [module-alias](https://www.npmjs.com/package/module-alias) but is that not simply wasteful duplication since Typescript has a native [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) feature.  You can see this [configured here](https://github.com/mathisGarberg/angular-folder-structure/blob/762bedd8d9b1edc9ba60cd892ab1e7cb17e63c88/tsconfig.json#L16-L19) and [used here](https://github.com/mathisGarberg/angular-folder-structure/blob/762bedd8d9b1edc9ba60cd892ab1e7cb17e63c88/src/app/app.module.ts#L4-L5).  It adds clarity to a project and even a beginner would be able to understand the simple concept.

Clarity over brevity should be prefered, code needs to be readable especially when working in teams. Maybe `@app` is a bit ambiguous perhaps it might be better to rename it to `@example-app`.  Furthermore, for consistency we could replace all applicable paths to use the alias in every instance like the aforementioned ngrx example.  Thoughts?

**Comment by sharkeron** [comment]
Thanks for this repo. But I have a question.

When I building the dev server, to the console output some circular dependency errors. After reviewing the logs, I saw that complaining about `index.ts` in `src/app/core`. And yes, previously I have replaced the relative paths of imports to aliases.

How do I fix this errors without remove `index.ts`-s files?

**Comment by TomHAnderson** [comment]
@dougal83 Now that the documentation is in place I hope you will add your knowledge about aliasing directories using path mapping.  This technique is new to me so I don't have much to say about it.  

I would like to try to find common ground to differentiate features like path mapping:

This repository is the result of a single blog post.
Teaching someone about path mapping is not the same subject and would be a new blog post.
Teaching someone about using singular vs plural naming in their app would be a new blog post.

I would like to see this repository remain single-blog-post worthy.  Uncomplicated, to the point, and teaching a single principle.

**Comment by TomHAnderson** [comment]
@sharkeron your question is exactly what we're discussing here.  If we remove the alias as I'm promoting then your problem will go away.

**Comment by sharkeron** [comment]
@TomHAnderson it’s ok, but if I remove `index.ts` files and set imports with alias, build will be compiled successful. 

I don’t understand for what were added this files. Maybe I don’t know about this features in typescript. :(

**Comment by TomHAnderson** [comment]
@sharkeron Please follow this repo for the next couple days and I believe your issue will become fixed.

**Comment by TomHAnderson** [comment]
I think I've found a compromise!  In my latest PR I've removed the @app and @shared aliases and kept the @env alias.  This way we can continue to have an example of an aliased directory in the application but it is done in a very minor way.

**Comment by TomHAnderson** [comment]
@dougal83 I've come around and see the reasoning behind @app.  I hope you'll help in the discussion on my new thread: #61

**Comment by TomHAnderson** [comment]
Documentation for aliases is now an official PR:
https://github.com/mathisGarberg/angular-folder-structure/pull/63

https://github.com/mathisGarberg/angular-folder-structure/blob/5b891f95d3f0adf24997c46580ab91520b140f6d/path-alias.rst
