### ISSUE TITLE
The power of singular nouns (discussion)

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#14]
I am a firm proponent of using singular nouns throughout my application.  This prevents nonsense words like mooses and I believe it is easier for non-native english speaking developers.  

What this means for this project is I want to change all plural nouns in the directory structure to singular.  Such as 
- app
  - core
    - guard
    - interceptor
    - service
  - layout  
  - module
  - shared (not shareds)

This repository is used by a LOT of developers as the source of truth.  I believe this change will benefit them all.  It adds clarity and removes disambiguation.   Please comment.

**Comment by mathisGarberg** [comment]
Well. There are some great benefits of using singular nouns to describe the overall directory structure, but what really matters to me is that we're consistent throughout the application when going with the one or the other. What I've seen from other enterprise apps is a good combination between the two, and I can see this leading to confusion for new developers. I'm open for PR(s) here.

**Comment by TomHAnderson** [comment]
First off, thank you so much for your openness to my ideas.  I've only been programming 30ish years so what do I know :)  Thanks for your acceptance.

Today I'll create a PR with singular names for the directory structure.  I will not try to modify the code to use singular names.  That is a whole other debate.  So for now I'm happy that we can just change the directory names.

**Comment by mathisGarberg** [comment]
I'm always open to good ideas that directs this beginner project in the right direction. There's a lot of debatable issues regarding an application-structure, and there is no blueprint here. This repo should help developers by giving them an indication of a scalable structure, in order for them to figure what best suite their use-case.

Looking forward to see the changes. Thanks.

**Comment by dougal83** [comment]
+1 revert to plurals in line with angular norms.
