### ISSUE TITLE
Use component instead of page (discussion)

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#17]
Hello,

In the demo application for Angular there isn't a notion of a 'page' directory.  In the case of 'page' in this application it is a made up term.  I propose we move all 'page' directories into 'component' directories.

**Comment by TomHAnderson** [comment]
This is in addition to renaming page to component, I like using component-ui for things like ~/src/app/shared/component/*  ; so rename this dir to component-ui.  I don't see this standard used a lot but it makes sense to me, so let's discuss.

**Comment by mathisGarberg** [comment]
The pages are used to illustrate the different routes the application is made up of, and is based off of [this](https://medium.com/@motcowley/angular-folder-structure-d1809be95542) article.

**Comment by TomHAnderson** [comment]
My argument here is week and I'm fine with using `page` and `component` directories (`component` for page parts like the spinner).
