### ISSUE TITLE
Repository Description

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#23]
There is no description on this project right now.  I suggest adding one such as

"The project is based on best practices from the community, other github Angular projects and developer experience from production Angular projects."

**Comment by mathisGarberg** [comment]
I believe the current description is sufficient to get up and running with the project.

**Comment by mathisGarberg** [comment]
I believe the current readme file is suffiecent to help developers get an overview of both purpose and instructions of how to get started.

**Comment by TomHAnderson** [comment]
True!  But you can add a description to the github title for the app.  You can also add topics like 'Angular, Directory Structure' etc.

<img width="1024" alt="Screen Shot 2019-08-07 at 1 08 57 PM" src="https://user-images.githubusercontent.com/493920/62650867-fad10e80-b914-11e9-8eba-0e2564c635c2.png">
