### ISSUE TITLE
Docs about main.scss

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#27]
https://github.com/mathisGarberg/angular-folder-structure/blob/master/.documentation/theme.rst needs documentation about what `main.scss` does and how it's included in the app.

**Comment by TomHAnderson** [comment]
#53 makes this unnecessary.  However with #53 styles.scss could still use a tidy and docs on how you are implementing the themes.

**Comment by mathisGarberg** [comment]
I will start documenting the initialization of theming today.

**Comment by TomHAnderson** [comment]
I just moved themes to `~/src/styles/themes` because I feel all styles should be in the styles directory and organizing within that directory is beneficial.
