### ISSUE TITLE
Route structure in home.routing.ts

### ISSUE THREAD

**Issue by needsmorecoffee** [mathisGarberg/angular-folder-structure#31]
The child routes for the /dashboard/* route are defined using an empty path, no component, several children and no default. This means when you visit /dashboard/ you get a blank page. Wouldn't it be better to express these as either non-child routes with a default, or as child roots but with a root component at the top level?

`export const routes: Routes = [
    {
      path: '',
      children: [
        {
          path: 'home',
          component: HomeComponent
        },
        {
          path: 'projects/:id',
          component: ProjectDetailsComponent,
          resolve: {
            project: ProjectResolver
          }
        }
      ]
    },
];`

**Comment by TomHAnderson** [comment]
How about a redirect for `''` to `/dashboard/home`?

**Comment by mathisGarberg** [comment]
Will submit a change with a redirect to `/dashboard/home` as suggested

**Comment by mathisGarberg** [comment]
Pushed a fix just now.
