### ISSUE TITLE
Move documentation to readthedocs.org

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#39]
In order to separate the docs from the application and to provide a clean branch for readthedocs.org I need @mathisGarberg to do the following

- [x] Create an account at readthedocs.org (not .com) and post your username to this thread so I can add you as an administrator to https://angular-folder-structure.readthedocs.io/en/latest/

- [x] Delete these branches from the repository: develop, version-2, revert-18-feature/singular-directory-names (unnecessary and should not exist on this 'master' copy of the repository)

```
  git push origin --delete develop  
  git push origin --delete version-2  
  git push origin --delete revert-18-feature/singular-directory-names  
```

- [x] Create a new empty branch called `docs` with just a README.md in it as a placeholder.  I'll then be able to submit a PR to that branch with the docs.  Here's a script for that

```
  git checkout --orphan docs
```
Wait while git removes all the files to create the empty branch
```
  touch README.md
  git add README.md
  git commit -m "Initial Commit"
  git push origin docs
```

- [x] After you have been added as a readthedocs.org administrator please add the github commit hooks detailed here: https://docs.readthedocs.io/en/stable/webhooks.html

from readthedocs.org:
```
  You can use the following address to manually configure this webhook.
  readthedocs.org/api/v2/webhook/angular-folder-structure/94055/
```

**Comment by TomHAnderson** [comment]
Once the docs are on readthedocs we won't be handicapped by github's weak .rst support and can have a side menu and more.

**Comment by mathisGarberg** [comment]
Completed the mentioned steps. My username is MathisGarberg

**Comment by TomHAnderson** [comment]
readthedocs.org (not .com) says it can't find you.  Please double check your username

Existing Maintainers
toma42
Add Maintainer
Choose which user you would like to add.

User MathisGarberg does not exist
User:
MathisGarberg

**Comment by TomHAnderson** [comment]
The `docs` branch was not created correctly.  Instead of an --orphan branch it still has all the code from master in it.

Please delete the current branch then re-create it

```
  git push origin --delete docs
  git branch -D docs
  git checkout --orphan docs
```
wait until all the files have disappeared from your system....
```
  touch README.md
  git add README.md
  git commit -m "Initial Commit"
  git push origin docs
```

**Comment by mathisGarberg** [comment]
Will I have to delete the files manually?

**Comment by mathisGarberg** [comment]
The files aren't deleted automatically, but instead added to the staging area as new files.

**Comment by TomHAnderson** [comment]
When I did it I had to wait a minute.  To bypass this run

```
  git reset
  git add REAMDE.md
  git commit -m "Initial Commit"
  git push origin docs
```

By using reset it will remove all the other files from the pending commit
and you can just commit the one file.  I think once we get data in the docs
branch the files will remove and add properly.

**Comment by mathisGarberg** [comment]
Yeah. I unstaged the files and pushed the readme.
