### ISSUE TITLE
Login takes too much time.

### ISSUE THREAD

**Issue by mrinalkumarjha** [mathisGarberg/angular-folder-structure#4]
Hi mathis,
i am digging into your code and found one thing which is not clear to me.
When i click login spinner moving for long time approx 6 sec which is really high for static data authentication . It should not take too much time as uid and password is hardcoded we are not making any api request here. can you share why it is happening in your code.

![image](https://user-images.githubusercontent.com/3676282/51329894-6ac49800-1a9c-11e9-88c4-5746e73c3557.png)

![image](https://user-images.githubusercontent.com/3676282/51329680-06093d80-1a9c-11e9-84f5-84bf7733399e.png)

**Comment by dougal83** [comment]
It's just an arbitrary delay added for simulation: [delay(5000)](https://github.com/mathisGarberg/angular-folder-structure/blob/2d5ec676426a2fe2076c82508e579d62e6458501/src/app/modules/auth/pages/login/login.component.ts#L41)

**Comment by mrinalkumarjha** [comment]
ya thanks i missed that line. there are 5 sec delay. 

![image](https://user-images.githubusercontent.com/3676282/51387094-e2510080-1b4a-11e9-9a1a-b77831e01c71.png)

**Comment by mrinalkumarjha** [comment]
closing issue as solved doubts.
