### ISSUE TITLE
Documentation Copyright

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#45]
I always want to ensure we're on the same page whenever a legal issue comes up.

Right now the copyright on the docs says
"© Copyright 2019 Mathis Garberg and contributors"

I'd like to change this to 
"© Copyright 2019 Mathis Garberg, Tom H Anderson, and contributors"

Give me a go-ahead and I'll submit a PR

**Comment by mathisGarberg** [comment]
I'm prepared to list you as a co-owner of the project based on your effort, but I'de like to know which legal issues you're reffering to. I still want to check incoming PRs made to this repository, before publishing them to master, so I'm aware of the incoming changes. You have however taken this repo to the next level, and such an effort should be rewarded.

**Comment by TomHAnderson** [comment]
For legal issues usually means anytime I would put your name as the author and I could also put my name.  I'm generally only concerned about attribution.  Because this is open source there are very few legal issues but I don't want  to presume and that's why I asked first.

I'm not asking for commit permissions on this repo.  I feel strongly that the structure we have in place now is working very well.

**Comment by mathisGarberg** [comment]
Yeah, I agree. The structure we have in place here is strong, and consent in using my name concerning general attribution regarding the project. Thanks for asking.
