### ISSUE TITLE
Webhook not triggering for readthedocs

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#47]
After merging #46 please see https://readthedocs.org/projects/angular-folder-structure-dev/builds/ to ensure a build started.  If not please investigate the webhook config.

**Comment by TomHAnderson** [comment]
Checked on this after the merge and auto builds are not triggered on RTD.  The best way to debug this is to make a small change to the docs branch then push it then check RTD builds.

**Comment by mathisGarberg** [comment]
Any updates on this?

**Comment by TomHAnderson** [comment]
This is something you as the repository owner must complete.  Please review the steps here  https://docs.readthedocs.io/en/stable/webhooks.html and test.

**Comment by mathisGarberg** [comment]
Okey. I started documenting the initialization process of themes and will probably complete this tomorrow. Then I’ll move on to fixing this issue.
