### ISSUE TITLE
README.md image of running app

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#49]
I recommend changing the height of the image on README.md to half of its current height.  This will allow mobile to show the whole readme file instead of using 'read more' when we really don't have much text in the readme.

![Screen Shot 2019-08-09 at 9 21 56 PM](https://user-images.githubusercontent.com/493920/62816951-f743b000-baeb-11e9-8372-f8cc708264ae.png)

**Comment by TomHAnderson** [comment]
![Uploading Screen Shot 2019-08-09 at 9.21.56 PM.png…]()

**Comment by mathisGarberg** [comment]
This is a good point. Will update the README with a cropped image in place.
