### ISSUE TITLE
How to use admin and client module using this structure.

### ISSUE THREAD

**Issue by mrinalkumarjha** [mathisGarberg/angular-folder-structure#5]
i am trying to use this structure for my app where i need admin part where admin can manage client. i dont understand how to separate admin module from client. i have created a new admin module inside modules. now how to route admin dashboard and their subsequent pages like add user.
it will be helpful if you add admin section in your code.
![image](https://user-images.githubusercontent.com/3676282/52630668-ddc9fe80-2ee2-11e9-8570-1d6fa68f9bda.png)

**Comment by mathisGarberg** [comment]
Hi, @mrinalkumarjha.

I assume that you want to use the content of the admin-component as a "wrapper" for the separate admin-pages. You can easily achieve this by changing your structure like this:

``
|-- admin
|      |-- [+]
|      |-- pages
|      |      |-- add-user
|      |-- admin.module.ts
|      |-- admin-routing.module.ts
|      |-- admin.component.ts
``

**Comment by mrinalkumarjha** [comment]
Hi Mathis,
 Thanks for replying. I am trying to use 2 layout one for admin module and one for client module. please suggest how to achieve this. it will be helpful for me if you update code. it must be helpful for others also.
