### ISSUE TITLE
Change theme directory to styles

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#53]
By default the `main.scss` file in a brand new Angular installation is called `styles.scss`.  Instead of creating our own convention for this `main.scss` I propose we move `~/src/theme` to `~/src/styles` to be used by the existing and default `styles.scss`.

**Comment by TomHAnderson** [comment]
New documentation: https://github.com/mathisGarberg/angular-folder-structure/blob/407bcbfc5ca48b6abc1898f408ed400e6fd0d64f/styles.rst

**Comment by dougal83** [comment]
+1 revert to themes folder in line with angular norms.
