### ISSUE TITLE
Change README.md title

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#57]
I'd like to propose changing the title for the application title in the README.md from

Highly Scalable Angular Folder Structure
=============================

to 

Angular Folder Structure - Highly Scalable
===============================

or my personal preference: 

Angular Folder Structure
==================

**Comment by mathisGarberg** [comment]
The title was a result of this project being based on the medium article i wrote, and should provide the user with a scalable folder structure. But I have to agree that the second option is a better fit.
