### ISSUE TITLE
Should we create all models inside core or module level.

### ISSUE THREAD

**Issue by mrinalkumarjha** [mathisGarberg/angular-folder-structure#6]
In this architecture you have created model inside core. if i have created 10 modules should we create model for each module inside core or at module level. please suggest.

![image](https://user-images.githubusercontent.com/3676282/52647255-614b1600-2f0a-11e9-82f3-e455590895ee.png)

**Comment by mathisGarberg** [comment]
Hi, @mrinalkumarjha.

The "model" folder of this architecture defines application-wide models, which can be used across several components in the application. When dealing with models explicitly tied to an individual module, it's logical to place them inside the module' folder. I've kept scalability in mind when designing this structure.

**Comment by mrinalkumarjha** [comment]
yes making sense...
