### ISSUE TITLE
core vs lib (discussion)

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#61]
The term `core` does not exist in many top-level applications.  The term `lib` does.  I've been rolling around the idea of using lib instead of core.

Angular is oddly structured.  For instance Zend Framework 2 uses this structure:
```
.
├── config
│   └── autoload
├── data
│   └── cache
├── module
│   └── Application
│       ├── config
│       ├── src
│       │   └── Controller
│       ├── test
│       │   └── Controller
│       └── view
│           ├── application
│           │   └── index
│           ├── error
│           └── layout
└── public
    ├── css
    ├── fonts
    ├── img
    └── js
```

The homolog to Angular's app.module is stored inside the module directory and is therefore a module equal to the rest of the modules in the application.

Angular does not work this way and this is the root of the reason this project exists.  Any new module we create e.g. `~/src/app/module/about` comes with a built-in subdirectory.  `App` doesn't have this and using `~/src/app/app/code-here` is just silly.  And that's why we use `~/src/app/core/code-here`.

So I'm thinking about `~/src/app/lib/code-here` 

The use of `lib` is more geeky and "low-level".  I think the term will be accepted in the community.  The term `core` is not as "computer science"ey.

When I came on to this project there was a discussion of aliasing `core` to `@app` and that's not an idea I've ignored.  Should we change `core` to `lib` then aliasing `lib` to `@app` would be necessary and we would document how to do that as part of the `install` section of the `lib` documentation.

I'm sorry if I'm only just realizing the real use of @app while you've known it all along.

I'd like feedback on this idea please.

**Comment by dougal83** [comment]
This project is one way of structuring an angular project that can be scaled and as such will naturally follow the programming language in use.  Everything should only be considered in context, bringing baggage from other ecosystems(i.e. Zend) should be cautioned against.

Libraries are commonly brought in off the shelf to be used. See [example](https://www.drupal.org/docs/8/modules/libraries-api-8x) from the popular Drupal framework.  Having a core module understandable denotes a module that holds the app's essential code.  If anything it sounds like you're arguing to essentially drop the modules folder from this project giving core, shared, <additional feature modules> at the same level, which makes sense.  The flattened modules approach is growing on me as I've been using [ngrx recently](https://github.com/ngrx/platform/tree/master/projects/example-app/src/app).

So calling anything library that is not for external libraries is totally off the cards IMO.... That's the theory, here is the real reason you could have googled... [Angular libraries](https://angular.io/guide/libraries) exist and are for importable functionality.

@mathisGarberg has done a great job with this project and has shown good judgement.  Long may it continue.. *cough flatten the modules folder. :)

**Comment by TomHAnderson** [comment]
| So calling anything library that is not for external libraries is totally off the cards

I agree.  Thanks for the input!  I'll no longer consider `lib` for a `core` replacement and I'll do more research and document how to use aliasing in the app in a way which does not require index.md in every directory.
