### ISSUE TITLE
Flattening the module directory

### ISSUE THREAD

**Issue by TomHAnderson** [mathisGarberg/angular-folder-structure#65]
@dougal83 suggested flattening the modules.  We probably have different ideas for what that means, but here's some brainstorming output that may be useful to the conversation.

I come from a PHP Zend Framework (1 & 2) background.  In Zend Framework the `app` is part of the modules directory.  Here we have a `core` directory because the `app` is the project source root because `ng` creates all its files in `~/src/app`.  

Any module can be the starting point of an application.  The configured module is bootstrapped (and ran?) in the [`~/src/main.ts`](https://github.com/mathisGarberg/angular-folder-structure/blob/master/src/main.ts#L5-L12) file.  

Even when you change `~/angular.json` projects.appname.sourceRoot value `ng` will still add the `app` suffix.  (note the angular.json property `prefix` refers to the code prefix for selectors, etc. and does not apply to this naming).  

I would like to explore the idea of this directory structure:

```
.
├── e2e
│   └── src
├── media
└── src
    ├── app -> . (symlink; added to .gitignore)
    ├── assets
    ├── environments
    ├── module
    │   ├── app
    │   │   └── layout
    │   ├── data
    │   └── shared
    └── styles
``` 

Setting up this directory structure

```
mkdir media
mkdir src/module
mkdir src/styles
mv src/app src/module
mkdir src/module/app/layout
cd src && ln -s . app & cd .
sed -i .bak 's/.\/app/.\/module\/app/g' src/main.ts
ng generate module module/Shared
ng generate module module/Data
json --version || npm install -g json
json -f tsconfig.json -I -e "this.compilerOptions.paths = {}"
json -f tsconfig.json -I -e "this.compilerOptions.paths['@app/*'] = ['module/app/*']"
json -f tsconfig.json -I -e "this.compilerOptions.paths['@shared/*'] = ['module/shared/*']"
json -f tsconfig.json -I -e "this.compilerOptions.paths['@env/*'] = ['environment/*']"
json -f tsconfig.json -I -e "this.compilerOptions.paths['@data/*'] = ['module/data/*']"
```

Although a little bit of file moving around is necessary this structure has these advantages:

* All modules are stored inside the module directory 
* All modules are on the same level (flat?)
* The special directory `app` is no longer the home of the app.module and the new home of the app.module can have subdirectories thereby removing the `core` module

Thanks for reading!  Please leave feedback

**Comment by dougal83** [comment]
> I come from a PHP Zend Framework (1 & 2) background.

I think our differing backgrounds are a source of friction with our ideas (Ada95, C#).  Personally I seek to follow convention first and foremost, while bringing the lightest touch from previous languages.  This project was one of the various examples I explored to familiarise myself with angular styles that scale nicely.

Here are examples of the aforementioned flattened modules structure in my view. Firstly, one level for all modules(works well for smaller apps):
````
.
├── e2e
│   └── src
└── src
    ├── app
    │   ├── auth (feature module, typical)
    │   ├── books (feature module)
    │   ├── core (core module, typically includes data services)
    │   ├── material (UI module)
    │   └── shared (items like pipes, etc)
    ├── assets
    ├── environments
    └── themes (deliberately named, utilise angular theming)
````

Inline with this project, a more scalable but can lead to questions if the previous example is enough:
````
.
├── e2e
│   └── src
└── src
    ├── app
    │   ├── core
    │   ├── features (or modules)
    │   │   ├── auth (would it be better under app?)
    │   │   └── books (need to justify features/modules folder, feature rich app)
    │   ├── material (UI module)
    │   └── shared (items like pipes, etc)
    ├── assets
    ├── environments
    └── themes
````

Personally I'm finding the one level in the first example above more than adequate in my work.  Anything requiring more thought is typically involving large teams that will make more use of the modular nature of Angular.

I'm getting the feeling that you just don't like there being a core folder. :)  I think it helps to consider the the idea that core is essential items, shared optional reusable items and features are additional functionality.  Naming these three items as such signifies the function and importance.  Just bunging everything into a modules folder for the sake of grouping like items together is missing the nuance provided by the labels used.  Hope that helps you understand where I'm coming from.  What I'm really questioning here is that do we even need a features/modules folder?

**Comment by TomHAnderson** [comment]
I really appreciate your trees, @dougal83 

You're 100% right; I don't like the core directory.  Renaming it wouldn't matter; I don't like that we need a directory separate from the module in order to store code which belongs in that module.  In fact the need for a core directory is my biggest problem with ng generated Angular applications.  I want a directory structure like `~/src/modules/app/guards`.

I'm coming around on using more plural.  Specifically `modules` and `themes`.  And I like having them all in the same directory.  In fact I don't think any modules, including app, should live outside the `modules` directory.  

```
.
├── e2e
│   └── src
├── media
└── src
    ├── app -> . (symlink to src)
    ├── assets
    ├── environments
    ├── modules
    │   ├── app
    │   │   └── layout
    │   ├── data
    │   └── shared
    └── styles
        └── themes
```

In this tree I've included themes.  I was thinking of themes in the styles directory all along but it was only assumed and here it is specific.  

The data module doesn't actually import or export anything.  I think of it as analogous to a `Database`, or the short hand I use, `Db` module.  But it could have other classes which are specific to the database and that's why I like it as a module.

Regarding `features` vs `modules` I prefer to call them as they are, that is, `modules`.
In your trees, @dougal83 , you still use the `~/src/app`.  I'm trying to correct the mis-placed `app` module in my directory tree because I think it is a critical error by the `ng` team.  I'm willing to defend this unusual symlink for ~/src/app to ~/src.  `ng` was trying to make a very slim tree and put their starting module, app.module, in a position where it does not comply with every other module in regards to supporting code, hence the `core` module.

p.s.
Because this repository didn't have any documentation I feel my process of breaking the application down with a fine toothed comb until I understand and can document it is making this a strong resource.

**Comment by TomHAnderson** [comment]
What I'm seeing with these posts is we agree with the reason for the extended directories and modules which are defined in the documentation, more or less.  Their arrangement is now the primary difference.

What if, as part of the documentation, after describing all the parts, we have named directory structures for arranging those parts?  Of course the first and default one would be this module.  We could give it a name like "Mathis".  Then I'd like a whole doc page for my structure, "Neolithic".  And we can have more doc pages each detailing a structure from which to hang the directory and module parts.

**Comment by dougal83** [comment]
@TomHAnderson I appreciate your new docs.  Could they perhaps be placed in a docs folder to keep the project root from being cluttered?  I'm surprised that you hadn't gathered them all up already TBH. :)

I have to say that I extremely disagree with deviating from the standard Angular structure of using ./src/app.  I don't see a valid reason here for doing as such.  This [example](https://github.com/tomastrajan/angular-ngrx-material-starter/tree/master/projects/angular-ngrx-material-starter/src) is an ideal pattern that I'd expect to see in an Angular app.  Throwing in a symlink that would be alien to many learners is also a step too far.

I think it is time to call it a day here for me.  My personal preferences lead me to feel that I no longer consider this project as a good example to follow for beginners.  I wish you the best of luck evolving this project to help others.

**Comment by TomHAnderson** [comment]
The docs are all alone in the docs branch.  They are hosted on readthedocs and don't clutter the app.

Very sorry to lose you @dougal83

**Comment by TomHAnderson** [comment]
p.s. the link to my example was on my personal development readthedocs site and not the live site for this repo.  So it was an example
