### ISSUE TITLE
List alternatives to this repo

### ISSUE THREAD

**Issue by dougal83** [mathisGarberg/angular-folder-structure#66]
When learning, I think it would be helpful for people to see a variety of approaches.  Perhaps we can point to similar angular repos for people to get a feel for the language.

Examples like:

- [starter-kit](https://github.com/ngx-rocket/starter-kit)
- [angular-ngrx-material-starter](https://github.com/tomastrajan/angular-ngrx-material-starter)
- [angular-starter](https://github.com/PatrickJS/angular-starter)
- [Angular-Full-Stack](https://github.com/DavideViolante/Angular-Full-Stack)

**Comment by TomHAnderson** [comment]
In my latest pr for docs I include a furthur-reading page and agree these alt approaches should be included.
