### ISSUE TITLE
How to use admin and client module using this structure.

### ISSUE THREAD

**Issue by mrinalkumarjha** [mathisGarberg/angular-folder-structure#7]
Hi Mathis,
 Thanks for replying. I am trying to use 2 layout one for admin module and one for client module. please suggest how to achieve this. it will be helpful for me if you update code. it must be helpful for others also.

_Originally posted by @mrinalkumarjha in https://github.com/mathisGarberg/angular-folder-structure/issues/5#issuecomment-466992032_

**Comment by mathisGarberg** [comment]
Hi!

Will get back to you as soon as I get  some time on my hand :blush: 

Mathis

**Comment by TomHAnderson** [comment]
This is a question about Route Guards.  These are addressed in the directory structure at `~/src/app/core/guards`

Here is a good article to help you create and deploy your own route guards: https://medium.com/@ryanchenkie_40935/angular-authentication-using-route-guards-bf7a4ca13ae3
