### ISSUE TITLE
Approach to integrate generated api module

### ISSUE THREAD

**Issue by dougal83** [mathisGarberg/angular-folder-structure#8]
Hi Mathis

I really appreciate your repo here.  I was wondering how you would approach integration of a generated api such as [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli).  I was wondering about your thoughts on where to locate the generated module and if to include via the core module?  [Example Code](https://github.com/dougal83/generated-api-example/tree/master/generated-api)

Looking forward to hearing your approach.

Kind regards
Doug

**Comment by mathisGarberg** [comment]
Hi Doug!

Well. You would normally place all of your singleton services in the Core Module, as this module loads only once at application startup. This will probably also be the case for the generated ApiModule(s) as their also restricted to load once when the app loads. So keeping this logic in the Core Module, would probably be the best solution.

Best,
Mathis
