### ISSUE TITLE
@ngrx/store

### ISSUE THREAD

**Issue by Hectix** [mathisGarberg/angular-folder-structure#84]
Maybe we can add @ngrx/store as it becomes a must-have for large angular apps?

**Comment by TomHAnderson** [comment]
I vote against adding more libraries.  This project has a distinct goal of application structure.  Although it has some 'extra' libraries they are beside the central goal of finding reasons for new directory structure parts and defining ways to arrange them.

**Comment by Arti3DPlayer** [comment]
@TomHAnderson It will be nice to add @ngrx/store example for large application... I faced this issue right now and I'm not sure in what direction I should move:

https://stackoverflow.com/questions/59759844/redux-how-to-organize-store-in-big-application
