### ISSUE TITLE
Theme preference 

### ISSUE THREAD

**Issue by Hectix** [mathisGarberg/angular-folder-structure#87]
I don't see a code responsible for setting and retrieving a theme preference from let's say a localstorage. So now, when the user refresh the app, he always sees the light theme. I think it would be great to have that kind of functionality.

**Comment by mathisGarberg** [comment]
Sounds like a good feature that isn't too hard to implement in a good manner. Will surely look i to it at some point

**Comment by Hectix** [comment]
#88

**Comment by Hectix** [comment]
@mathisGarberg Can you take a look at the #88, please?

**Comment by mathisGarberg** [comment]
I've reviewed your commit now, and everything seems to work fine. I'm sorry for the delayed response.
